MASTERDIR=	${.CURDIR}/../u-boot-master
PORTREVISION=	1
MODEL=		pinebookpro
BOARD_CONFIG=	pinebook-pro-rk3399_defconfig
FAMILY=		rk3399
EXTRA_PATCHES=	${.CURDIR}/files/

.include "${MASTERDIR}/Makefile"
