# $FreeBSD: head/sysutils/u-boot-pinebookpro/Makefile 556066 2020-11-22 17:37:40Z manu $

MASTERDIR=	${.CURDIR}/../u-boot-master

EXTRA_PATCHES=	${.CURDIR}/files/

U_BOOT_SLAVE_PORTREVISION_2020.10=	1

MODEL=		pinebookpro
BOARD_CONFIG=	pinebook-pro-rk3399_defconfig
FAMILY=		rk3399

.include "${MASTERDIR}/Makefile"
